### ISSUE TITLE
[Observe] add Observability for agent-docs-creator

### ISSUE THREAD

**Issue by GALLLASMILAN** [i-am-bee/beeai#388]
This agent is built on our beeai typescript fw. The observability should work for this one. 
Check the server and set envs if they are not correctly set yet. 

The current [**collector filter**](https://github.com/i-am-bee/beeai/blob/main/apps/beeai-server/src/beeai_server/domain/collector/base.yaml#L20).

```
filter/phoenix:
    traces:
      span:
        - 'resource.attributes["service.namespace"] != "beeai-agent-provider"'
        - 'instrumentation_scope.name == "acp.shared.session" or instrumentation_scope.name == "acp"'
```
